modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "meanmobs"
version = "${version}"
displayName = "Mean Mobs"
authors = "iSeeEthan"
description = '''
This mod enhances the Vanilla Mob behavior!
'''
logoFile = "logo2.png"

[[dependencies.meanmobs]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.meanmobs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.11]"
ordering = "NONE"
side = "BOTH"

[[dependencies.meanmobs]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "meanmobs.mixins.json"
